### ISSUE TITLE
Tracking: ESLint v9 Support

### ISSUE THREAD

**Issue by Abhiek187** [Abhiek187/abhiek187.github.io#597]
Tracking dependencies that need to be updated to support ESLint v9:

- [x] [eslint-plugin-react](https://github.com/jsx-eslint/eslint-plugin-react): supported as of [v7.35.0](https://github.com/jsx-eslint/eslint-plugin-react/releases/tag/v7.35.0)
- [x] [eslint-plugin-react-hooks](https://github.com/facebook/react/tree/main/packages/eslint-plugin-react-hooks): supported as of [v5.0.0](https://github.com/facebook/react/releases/tag/eslint-plugin-react-hooks%405.0.0)
- [x] [typescript-eslint](https://github.com/typescript-eslint/typescript-eslint): supported as of [v8.0.0](https://github.com/typescript-eslint/typescript-eslint/releases/tag/v8.0.0)

```
npm error code ERESOLVE
npm error ERESOLVE could not resolve
npm error
npm error While resolving: eslint-plugin-react-hooks@4.6.2
npm error Found: eslint@9.7.0
npm error node_modules/eslint
npm error   dev eslint@"^9.7.0" from the root project
npm error   peer eslint@"^6.0.0 || ^7.0.0 || >=8.0.0" from @eslint-community/eslint-utils@4.4.0
npm error   node_modules/@eslint-community/eslint-utils
npm error     @eslint-community/eslint-utils@"^4.2.0" from eslint@9.7.0
npm error     @eslint-community/eslint-utils@"^4.4.0" from @typescript-eslint/utils@7.16.1
npm error     node_modules/typescript-eslint/node_modules/@typescript-eslint/utils
npm error       @typescript-eslint/utils@"7.16.1" from typescript-eslint@7.16.1
npm error       node_modules/typescript-eslint
npm error         dev typescript-eslint@"^7.16.1" from the root project
npm error       2 more (@typescript-eslint/eslint-plugin, @typescript-eslint/type-utils)
npm error   2 more (eslint-plugin-react, eslint-plugin-react-refresh)
npm error
npm error Could not resolve dependency:
npm error peer eslint@"^3.0.0 || ^4.0.0 || ^5.0.0 || ^6.0.0 || ^7.0.0 || ^8.0.0-0" from eslint-plugin-react-hooks@4.6.2
npm error node_modules/eslint-plugin-react-hooks
npm error   dev eslint-plugin-react-hooks@"^4.6.2" from the root project
npm error
npm error Conflicting peer dependency: eslint@8.57.0
npm error node_modules/eslint
npm error   peer eslint@"^3.0.0 || ^4.0.0 || ^5.0.0 || ^6.0.0 || ^7.0.0 || ^8.0.0-0" from eslint-plugin-react-hooks@4.6.2
npm error   node_modules/eslint-plugin-react-hooks
npm error     dev eslint-plugin-react-hooks@"^4.6.2" from the root project
npm error
npm error Fix the upstream dependency conflict, or retry
npm error this command with --force or --legacy-peer-deps
npm error to accept an incorrect (and potentially broken) dependency resolution.
```

```
npm error code ERESOLVE
npm error ERESOLVE could not resolve
npm error
npm error While resolving: typescript-eslint@7.16.1
npm error Found: eslint@9.7.0
npm error node_modules/eslint
npm error   dev eslint@"^9.7.0" from the root project
npm error   peer eslint@"^6.0.0 || ^7.0.0 || >=8.0.0" from @eslint-community/eslint-utils@4.4.0
npm error   node_modules/@eslint-community/eslint-utils
npm error     @eslint-community/eslint-utils@"^4.2.0" from eslint@9.7.0
npm error     @eslint-community/eslint-utils@"^4.4.0" from @typescript-eslint/utils@7.16.1
npm error     node_modules/typescript-eslint/node_modules/@typescript-eslint/utils
npm error       @typescript-eslint/utils@"7.16.1" from typescript-eslint@7.16.1
npm error       node_modules/typescript-eslint
npm error         dev typescript-eslint@"^7.16.1" from the root project
npm error       2 more (@typescript-eslint/eslint-plugin, @typescript-eslint/type-utils)
npm error   2 more (eslint-plugin-react, eslint-plugin-react-refresh)
npm error
npm error Could not resolve dependency:
npm error peer eslint@"^8.56.0" from typescript-eslint@7.16.1
npm error node_modules/typescript-eslint
npm error   dev typescript-eslint@"^7.16.1" from the root project
npm error
npm error Conflicting peer dependency: eslint@8.57.0
npm error node_modules/eslint
npm error   peer eslint@"^8.56.0" from typescript-eslint@7.16.1
npm error   node_modules/typescript-eslint
npm error     dev typescript-eslint@"^7.16.1" from the root project
npm error
npm error Fix the upstream dependency conflict, or retry
npm error this command with --force or --legacy-peer-deps
npm error to accept an incorrect (and potentially broken) dependency resolution.
```

**Comment by Abhiek187** [comment]
Only took 6 months, but it's done!
